export const genreConstants = [
    { value: 'alternative', label: 'Alternative' },
    { value: 'blues', label: 'Blues' },
    { value: 'classical', label: 'Classical' },
    { value: 'country', label: 'Country' },
    { value: 'dance', label: 'Dance' },
    { value: 'electronic', label: 'Electronic' },
    { value: 'hip-hop', label: 'Hip-hop' },
    { value: 'indie', label: 'Indie' },
    { value: 'jazz', label: 'Jazz' },
    { value: 'metal', label: 'Metal' },
    { value: 'pop', label: 'Pop' },
    { value: 'punk', label: 'Punk' },
    { value: 'reggae', label: 'Reggae' },
    { value: 'rap', label: 'Rap' },
    { value: 'rock', label: 'Rock' },
    { value: 'r&b', label: 'R&B' },
    { value: 'soul', label: 'Soul' },
]